default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('HOST_PORT_DB') %>
  port: 5432
  username: <%= ENV.fetch('USERNAME_DB') %>
  password: "!Bruno1234"
  pool: 5

development:
  <<: *default
  database: book_store_development

test:
  <<: *default
  database: book_store_test
