default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['HOST_PORT_DB'] || '127.0.0.1' %>
  username: <%= ENV['USERNAME_DB'] || 'postgres' %>
  password: <%= ENV['PASSWORD_DB'] || '!Bruno1234' %>
  database: myapp_development
  pool: 5

development:
  <<: *default
  database: book_store_development

test:
  <<: *default
  database: book_store_test
